name: weather_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  intl: ^0.19.0
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/images/
